export const SET_LOADING='SET_LOADING';
export const SET_QUIZ_STATUS='SET_QUIZ_STATUS';
export const INIT_QUESTIONS='INIT_QUESTIONS';
export const SET_QUESTION_INDEX='SET_QUESTION_INDEX';
export const SET_SCORE='SET_SCORE';
export const SET_ERROR='SET_ERROR';